name: rekmas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.17
  firebase_core: ^1.17.0
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.15
  flutter_staggered_grid_view: ^0.4.0
  provider: ^6.0.2
  path_provider: ^2.0.10
  image: ^3.1.3
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png



